name: scp copy folder to remote via SSH

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup demo
        run: |
          mkdir test
          touch test/oof.txt
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release/0.2.0
        with:
          local: test
          remote: home/rabi
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY}}
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release/0.2.0
        with:
          local: test/oof.txt
          remote: home/rabi
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_KEY}}
        env:
          CI: true
