name: Java CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file ssh key
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.PRIVATEkEY }}
        local: "home/zombie/rabi/test.xml"
        remote: "home/rabi"