name: Java CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file ssh privatekeys
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.SSH_KEY }}
        source: "home/zombie/project/19July2020/21July2020/thingsboard/application/nepal.tar"
        target: "home"