name: SCP
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: SCP file transfer
      uses: ./
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
      with:
        source: home/zombie/project/19July2020/21July2020/thingsboard/test.txt/
        target: "/home/rabi/"